### PR TITLE
Bucket Sort Algorithm in Go Language

### PR DESCRIPTION
**Pull request by jawadkhanpk**
## Language Opted?
- [x] Go

## Number of files added or updated?
- 1 file added : BucketSort.go

## Name of these files?

- DSA-Essentials/main/Algorithms/Sorting/Bucket_Sort/BucketSort.go

## Checklist
- [x] I was assigned for this otherwise my PR will be rejected.
- [x] I've read the contribution guidelines.
- [x] I've written code by myself. No Plagiarism allowed
- [x] I've referred the correct issue number.
- [x] I've filled up this entire template correctly.

🌟 this repository and support.

### CODE REVIEW

**Comment by jawadkhanpk** [comment]
@Jatin-Shihora Please check how it looks

**Review by Jatin-Shihora — CHANGES_REQUESTED** [review]
Please add some comments in the code for a better explanation of your algo

**Comment by jawadkhanpk** [comment]
Hi, Please see I added some comments in a code

**Review by Jatin-Shihora — APPROVED** [review]

**Comment by Jatin-Shihora** [comment]
@jawadkhanpk Please add some meaningful comments like what the function does instead of just mentioning the function name again in the commented part

**Review by Jatin-Shihora — CHANGES_REQUESTED** [review]
@jawadkhanpk Please add some meaningful comments like what the function does instead of just mentioning the function name again in the commented part

**Comment by Jatin-Shihora** [comment]
@jawadkhanpk The bot has triggered the timer if this is not resolved within 5 days i.e till 25th Oct 10:11 AM, the pull request will be nullified and you will be revoked from the related issues of this pull request.

from MasterTimer bot~

**Comment by Jatin-Shihora** [comment]
The pull request has been rejected since there was no improvement

**Pull request closed without merging**
