### PR TITLE
Implementation of BucketSort Algorithm in Javascript

### PR DESCRIPTION
**Pull request by jawadkhanpk**
## Language Opted?
- [x] JavaScript

## Number of files added or updated?
- 1 file added: BucketSort.js

## Name of these files?

- [Algorithms => Sorting => Bucket_Sort => BucketSort.js]

## Checklist
- [x] I was assigned for this otherwise my PR will be rejected.
- [x] I've read the contribution guidelines.
- [x] I've written code by myself. No Plagiarism allowed
- [x] I've referred to the correct issue number.
- [x] I've filled up this entire template correctly.

🌟 this repository and support.

### CODE REVIEW

**Comment by jawadkhanpk** [comment]
Hi @Jatin-Shihora Please see and let me know if it needs any improvement. Now I followed the proper guidliness that was mentioned in Readme.md

**Comment by Jatin-Shihora** [comment]
@jawadkhanpk It's all good now. Happy coding ^_^

**Comment by jawadkhanpk** [comment]
Thanks nice to work with you

**Review by Jatin-Shihora — APPROVED** [review]
Nicely Implemented

**Comment by jawadkhanpk** [comment]
please see my other pull request as weel #4

**Pull request merged**
